# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1302Z0kQFGGhsUSr4-zh0h9T9noMibBBW
"""

import streamlit as st
st.markdown("Created by: Satyush Mohapatra")
st.markdown("---")

import PyPDF2
import re
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.metrics.pairwise import cosine_similarity

def extract_text(file):
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        if page.extract_text():
            text += page.extract_text()
    return text

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', ' ', text)
    words = [w for w in text.split() if w not in ENGLISH_STOP_WORDS]
    return " ".join(words)

job_descriptions = {
    "Data Scientist": "python machine learning pandas numpy statistics data analysis",
    "Web Developer": "html css javascript react node frontend backend web",
    "ML Engineer": "python tensorflow pytorch nlp deployment"
}

st.title("Resume Screening System")

uploaded_file = st.file_uploader("Upload Resume", type=["pdf"])

if uploaded_file:
    resume_text = extract_text(uploaded_file)
    resume_clean = preprocess(resume_text)

    job_clean = {k: preprocess(v) for k,v in job_descriptions.items()}

    documents = [resume_clean] + list(job_clean.values())
    vectorizer = TfidfVectorizer(ngram_range=(1,2))
    tfidf_matrix = vectorizer.fit_transform(documents)

    scores = {}
    for i, role in enumerate(job_clean.keys()):
        score = cosine_similarity(tfidf_matrix[0], tfidf_matrix[i+1])[0][0]
        scores[role] = score

    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)

  st.subheader("Best Role")

if len(sorted_scores) > 0:
    st.write(sorted_scores[0][0])
else:
    st.write("No suitable role found")

    st.subheader("Ranking")
    for i,(role, score) in enumerate(sorted_scores,1):
        st.write(f"{i}. {role} → {round(score*100,2)}%")
if len(sorted_scores) > 0:
    best_role = sorted_scores[0][0]
else:
    best_role = "No match found"

resume_words = set(resume_clean.split())
job_words = set(job_clean[best_role].split())

missing_skills = list(job_words - resume_words)[:5]

st.subheader("Missing Skills")

if missing_skills:
    st.write(", ".join(missing_skills))
else:
    st.success("No missing skills ")
