# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1302Z0kQFGGhsUSr4-zh0h9T9noMibBBW
"""

import streamlit as st
st.set_page_config(layout="wide")
st.markdown("Created by: Satyush Mohapatra")
st.markdown("---")

import PyPDF2
import re
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
@st.cache_resource
def load_model():
    try:
        model = SentenceTransformer('all-MiniLM-L6-v2')
        return model
    except Exception as e:
        st.error(f"Model load failed: {e}")
        return None

model = load_model()
def extract_text(file):
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        if page.extract_text():
            text += page.extract_text()
    return text

def preprocess(text):
    text = text.lower()

    text = re.sub(r'[^a-z\s]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    text = text.replace("nodejs", "node")
    text = text.replace("reactjs", "react")

    words = text.split()

    words = [w for w in words if len(w) > 2]

    return " ".join(words)
SKILLS_DB = {
    "Data Scientist": ["python", "machine learning", "pandas", "numpy", "statistics"],
    "Web Developer": ["html", "css", "javascript", "react", "node"],
    "Android Developer": ["java", "kotlin", "android", "firebase"],
    "DevOps Engineer": ["docker", "kubernetes", "aws", "ci/cd"],
    "Cyber Security": ["network security", "penetration testing", "encryption"],
    "UI/UX Designer": ["figma", "wireframe", "prototyping", "design"],
    "General Professional": ["communication", "teamwork", "leadership"]
}
st.title("Resume Screening System")

uploaded_file = st.file_uploader("Upload Resume", type=["pdf"])

# ---------------- MAIN LOGIC ---------------- #
if uploaded_file:
    resume_text = extract_text(uploaded_file)

    if not resume_text.strip():
        st.error("Could not read resume properly")
        st.stop()

    st.write("Resume Preview:", resume_text[:300])

    resume_clean = preprocess(resume_text)

    job_clean = {k: preprocess(v) for k, v in SKILLS_DB.items()}

  # AI-based embeddings
if model is None:
    st.error("Model not loaded properly")
    st.stop()

try:
    resume_embedding = model.encode(resume_clean)
except Exception as e:
    st.error(f"Encoding failed: {e}")
    st.stop()
scores = {}

for role, text in job_clean.items():
    try:
    job_embedding = model.encode(text)
except Exception as e:
    st.error(f"Job encoding failed: {e}")
    st.stop()
    score = cosine_similarity([resume_embedding], [job_embedding])[0][0]
    scores[role] = score

    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True)

    threshold = 0.3

    # ---------------- BEST ROLE ---------------- #
    if sorted_scores and sorted_scores[0][1] >= threshold:
        best_role = sorted_scores[0][0]
    else:
        best_role = None

    st.header("Best Role")

    if best_role:
        st.success(best_role)
    else:
        st.error("No suitable role found")

    # ---------------- TOP 3 ROLES ---------------- #
    st.header("Top 3 Recommended Roles")

    top_3 = sorted_scores[:3]

    for i, (role, score) in enumerate(top_3, 1):
        st.write(f"{i}. {role} ({round(score*100,2)}%)")

    # ---------------- MATCH SCORE ---------------- #
    if best_role:
        score_percent = sorted_scores[0][1] * 100
        st.header("Resume Score")
        st.metric("Match Score", f"{round(score_percent,2)}%")

    # ---------------- FULL RANKING ---------------- #
    st.header("Ranking")

    for i, (role, score) in enumerate(sorted_scores, 1):
        st.progress(min(score, 1.0))
        st.write(f"{i}. {role} ({round(score*100,2)}%)")

    # ---------------- MISSING SKILLS ---------------- #
# MISSING SKILLS (AI CLEAN VERSION)

resume_words = set(resume_clean.split())

if best_role in SKILLS_DB:
    job_skills = SKILLS_DB[best_role]

    missing_skills = []
    for skill in job_skills:
        skill_words = skill.lower().split()
        
        if not all(word in resume_words for word in skill_words):
            missing_skills.append(skill)
else:
    missing_skills = []

st.header("Missing Skills")

if missing_skills:
    st.warning(", ".join(missing_skills))
else:
    st.success("No missing skills ")
