# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1302Z0kQFGGhsUSr4-zh0h9T9noMibBBW
"""

import streamlit as st
st.set_page_config(layout="wide")
st.markdown("Created by: Satyush Mohapatra")
st.markdown("---")

import PyPDF2
import re
from sklearn.metrics.pairwise import cosine_similarity

def extract_text(file):
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        if page.extract_text():
            text += page.extract_text()
    return text

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', ' ', text)
    words = [w for w in text.split() if w not in ENGLISH_STOP_WORDS]
    return " ".join(words)

job_descriptions = {
    "Data Scientist": "Python machine learning pandas numpy statistics",
    "Web Developer": "HTML CSS JavaScript React Node",
    "Android Developer": "Java Kotlin Android Studio",
    "DevOps Engineer": "Docker Kubernetes AWS CI/CD",
    "Cyber Security": "network security ethical hacking encryption",
    "UI/UX Designer": "Figma wireframe prototyping design",
    "General Professional": "communication teamwork problem solving leadership"
}

st.title("Resume Screening System")

uploaded_file = st.file_uploader("Upload Resume", type=["pdf"])

if uploaded_file:
    resume_text = extract_text(uploaded_file)
    resume_clean = preprocess(resume_text)

    job_clean = {k: preprocess(v) for k,v in job_descriptions.items()}

documents = [resume_clean] + list(job_clean.values())

vectorizer = TfidfVectorizer(ngram_range=(1,2))
tfidf_matrix = vectorizer.fit_transform(documents)

scores = {}

for i, role in enumerate(job_clean.keys()):
    score = cosine_similarity(tfidf_matrix[0], tfidf_matrix[i+1])[0][0]
    scores[role] = score
    sorted_scores = sorted(scores.items(), key=lambda x: x[1], reverse=True) 
threshold = 0.4

if len(sorted_scores) > 0 and sorted_scores[0][1] >= threshold:
    best_role = sorted_scores[0][0]
else:
    best_role = None

st.header(" Best Role")

if best_role:
    st.success(best_role)
else:
    st.error(" No suitable role found")
st.header("Top 3 Recommended Roles")

top_3 = sorted_scores[:3]

for i, (role, score) in enumerate(top_3, 1):
    st.write(f"{i}. {role} ({round(score*100,2)}%)")
if best_role:
    score_percent = sorted_scores[0][1] * 100
    st.header("Resume Score")
    st.metric("Match Score", f"{round(score_percent,2)}%")

resume_words = set(resume_clean.split())

st.header("Ranking")

for i, (role, score) in enumerate(sorted_scores, 1):
    st.progress(min(score, 1.0))
    st.write(f"{i}. {role} ({round(score*100,2)}%)")

if best_role in job_clean:
    job_words = set(job_clean[best_role].split())
else:
    job_words = set()

missing_skills = list(job_words - resume_words)[:5]

st.header("Missing Skills")

if missing_skills:
    st.warning(", ".join(missing_skills))
else:
    st.success("No missing skills ")
